### ISSUE TITLE
show release notes/splash screen on game start up

### ISSUE THREAD

**Issue by chrisfarms** [playmint/ds#100]
we should:

* be building the ds-test deployment from Github preview Releases instead of manual build
* populating useful release notes
* fetch the release notes in the game UI for the current build and show to player (if release notes available)
* player should not be shown the same notes twice (localstorage flag tied to version or something)
* splash message should note that mobile form factor not supported

**Comment by PlaymintDavid** [comment]
Yes please! It's odd not to be able to refer to a version number in a bug report!
