### ISSUE TITLE
Gracefully handle OOM in sandbox

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#1001]
We are currently having OOM issues causing plugins to fall over in sandbox

**Comment by Steedie** [comment]
During the performance testing task, we confirmed that when the sandbox runs out of memory, it causes the plugin UI to (sometimes) stop working.
Using the new [performance-testing](https://github.com/playmint/ds/pull/994) implementation, I'm currently:

- Lower total sandbox memory to trigger errors sooner
- Keep track of total memory usage in sandbox - during plugin update loop
- Properly handle plugin unloading/rebooting when we're out of memory
