### ISSUE TITLE
Set up Map deployment so it can happen from Github actions

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#1007]
Our github deployment workflow currently allows selecting which branch to deploy

we would also like to be able to select from a list of maps.

this can be achieved by
* supporting passing in the `MAP` as a [docker build argument](https://docs.docker.com/build/guide/build-args/) to the `contracts` Dockerfile
* then adding an [input param of type choice](https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/), to the workflow that passes it along to the build stage

**Comment by chrisfarms** [comment]
![Image](https://github.com/playmint/ds/assets/45921/1e6b862b-d1d9-4a0a-90fa-faf38a0af8a7)
