### ISSUE TITLE
Set up Github deploys to support 16 number of Hexwoods

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#1009]
we currently have github workflows for deploying ds-vanilla, ds-teal, etc .... we would like ds-hexwood1, ds-hexwood2.... ds-hexwoodN .... where N is a number TBC

**Comment by chrisfarms** [comment]
workflow updated in `main` see https://github.com/playmint/ds/commit/2e3d78b89e10285946372f4deee3394ffc0be0fa
