### ISSUE TITLE
Confirm that the github workflow provisioned instances are performant enough

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#1010]
Required before starting:

* #1009 
* #1008 
* #1007 

We are leaning on our azure deployments instead of our external playtests box.

We would like to know if

* we need to scale up to handle the increased number of deployments
* roughly the number of concurrent players each instance can handle before feeling laggy

**Comment by chrisfarms** [comment]
regular playtests are helping us gain confidence with this
