### ISSUE TITLE
Map with Tonk Attack, Hex Craft and Duck Burger all working

### ISSUE THREAD

**Issue by 5p0rt5BEArD** [playmint/ds#1033]
Dependant on

- #1017 
- #1016

**Comment by chrisfarms** [comment]
to get tonk-attack (working) on this shared map we will need to:

* test locally using `MAP=blah docker compose --profile tonk up`
* update the bit in the deployment chart [here](https://github.com/playmint/ds/blob/main/chart/templates/tonk.yaml#L1) that decides when to deploy tonk services based on map name
