### ISSUE TITLE
BlockOutOfRangeError upon starting avil

### ISSUE THREAD

**Issue by hypnoshock** [playmint/ds#1042]
There is some kind of race condition where sometimes we get a `BlockOutOfRangeError` from Anvil during startup which will prevent the map from being deployed or if running in docker will kill the `contracts` service entirely

```
ds-contracts-1  | (code: -32602, message: BlockOutOfRangeError: block height is 3 but requested was 2, data: None)) address=0x72919f511c32ff6f061c8fcb28581e5e11a7ba0c
```

**Comment by chrisfarms** [comment]
"looked into it" is a bit strong ... I stuck a `sleep` in there as it was annoying me 😅 

I also did `foundryup --version nightly-ca67d15f4abd46394b324c50e21e66f306a1162d` to run the same foundry version as the docker image ... I think that helped too
