### ISSUE TITLE
allow plugins to override building model

### ISSUE THREAD

**Issue by chrisfarms** [playmint/ds#1047]
we want to allow plugins to be able to alter the model used for buildings 

we think this will be useful for cases like switching between a "door open" and "door closed" model types (which don't exist yet)

**Comment by Steedie** [comment]
Would it make sense to use a retractable bollard as a door model?

![Image](https://github.com/playmint/ds/assets/27741109/36c494fb-fdfe-4ef5-9f0a-88794d151127)

**Comment by chrisfarms** [comment]
the proposed door/gate models have a direction (ie they face a particular way) ... so we should consider if we need to expose setting the rotation either via manifest or plugin or both
