### ISSUE TITLE
Allow switching Unit models from plugins

### ISSUE THREAD

**Issue by 5p0rt5BEArD** [playmint/ds#1050]
as either a replacement for (or complement to) #1044 we would like a similar plugin-driven ability to override the unit model

this is potentially blocked on  #1049

**Comment by chrisfarms** [comment]
something to think about in kickoff:

Our current "solution" for the fact that multiple plugins may be requesting changes to the same entity is to trust the plugin authors to do something sensible, like only affect things within a small range of a building.... in the case of switching colors, this means a unit might change color as it walks away from somewhere (little bit weird, but ok).... will changing entire model be too jarring / surprizing?
