### ISSUE TITLE
Tonk Attack : Nearby Units UI disappears off bottom of screen

### ISSUE THREAD

**Issue by 5p0rt5BEArD** [playmint/ds#1071]
Possible solutions:
- move to the left
- make part of anchored UI
- remove the craft input boxes from building ui once the game has started
- remove panel
- remove panel and show names above units

**Comment by chrisfarms** [comment]
for kick-off: We think that if we do #1122 , then we can disable the crafting UI in the tonk tower which will probably free up vertical space and resolve this issue
