### ISSUE TITLE
integrate rockaway map into croissant map

### ISSUE THREAD

**Issue by chrisfarms** [playmint/ds#1098]
* [ ] door model
* [ ] keccack for passwords bits

**Comment by hypnoshock** [comment]
- Map has been integrated into our 'croissant' map.
- Gates have been switched to door models in the `croissant-map-doors` and hasn't been merged in yet as we are planning to allow for colouring doors first
- The keccak password stuff didn't need changing in the end as Rockaway used encode function to get around it so it works
