### ISSUE TITLE
Player name input resets when world state updates

### ISSUE THREAD

**Issue by Steedie** [playmint/ds#1112]
When I am naming my player, the input box resets whenever the world state updates. It is also quite unclear after pressing enter to save that the name has been successfully changed.

https://github.com/playmint/ds/assets/27741109/573843ef-afae-453d-8ad4-f6a3bc0699fe

**Comment by chrisfarms** [comment]
is the player name actually used anywhere? I don't remember when/why it was added .... all the games seem to use the unit name not the player name

**Comment by Steedie** [comment]
> is the player name actually used anywhere? I don't remember when/why it was added .... all the games seem to use the unit name not the player name

It is used to show who deployed/placed a building: issue #613 
![image](https://github.com/playmint/ds/assets/27741109/89873aab-1ff6-4947-9656-369fad033a1f)

I think for a while the bit where it shows the player name instead of the address was accidentally overwritten but was recently(?) added back in.

**Comment by ldunnplaymint** [comment]
Turn off the player name input field
