### ISSUE TITLE
List ethereum websocket RPCs from this library

### ISSUE THREAD

**Issue by ghost** [playmint/ds#1117]
Will it possible to know which ethereum websocket RPCs are being triggered when we use the websocket client [here](https://github.com/playmint/ds/blob/main/core/src/cog.ts#L110). 
Will appreciate your help.

**Comment by chrisfarms** [comment]
the line of code linked is a graphql endpoint not an ethereum RPC endpoint, so I'm not sure if I understand the question.

what is it you are trying to do?
