### ISSUE TITLE
decouple deployment of Rules from deployment of Game

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#114]
we currently deploy all the Rules contracts bundled together with the Game contract in one go.

this was only as it was convenient during development and not suitable for a deployment to a real network as the combined contract size is too big.

we should separate deployment of Rules from the Game and ensure that we are below the contract size limit so that we can deploy to a public testnet

related: https://github.com/playmint/ds/issues/113

**Comment by chrisfarms** [comment]
closing as this no longer makes sense as a standalone task ... any refactoring will be done in #113
