### ISSUE TITLE
tile at entrace to hexcraft is out of range of model swap

### ISSUE THREAD

**Issue by chrisfarms** [playmint/ds#1140]
![Image](https://github.com/playmint/ds/assets/45921/4cf288a5-e647-4b05-a85e-d2538a34153f)

in this image I should be red, but I'm out of range of the color/model swapping 

potential solutions:

* increase the range
* move the HQ building up one tile so that it's not possible to be standing out of range when joining a team (this option is probably better for perfomance)

**Comment by Steedie** [comment]
In kick-off, we decided that increasing the `r` distance by 1 won't hurt the performance because the `r` axis range is checked like this:
```js
const inRange = unitCoords[1] >= hqCoords[1] - 1 && unitCoords[1] <= hqCoords[1] + 18;
```
Instead of checking every tile in a radius for the unit.
