### ISSUE TITLE
improved construction list UI

### ISSUE THREAD

**Issue by chrisfarms** [playmint/ds#1202]
* with multiple zones sharing all possible item/building kinds the construct drop-down UI is going to be unsuitable
* should be scoped at kick-off, but some ideas:
  * it could use a combo-box that live queries based on autocomplete
  * there could be some kind of allowlist setup by the zone owner
  * it could be a big single list, but infinite scrolling 
  * could be a modal with more comprehensive filters
  * etc

**Comment by ldunnplaymint** [comment]
Potentially use a combo box with a fuzzy search
