### ISSUE TITLE
cap "active" units per zone

### ISSUE THREAD

**Issue by chrisfarms** [playmint/ds#1205]
we want to cap the number of units actively bouncing around in each world somehow.

which implies there is some way of:

* knowing what "active" means (ie "unit has moved within the last 200 blocks")
* only allows spawning/migrating a unit into the world if there is "space"
* as part of spawning/migrating the "least active" unit is kicked out of the world (location moved to zone=0 or something like that)

we may also want a concept of "queuing" where your client waits for a slot and spawns in... this may be part of this task or may need splitting out if scope is too big. This queue could be a purely client-side race (easy), or could be something less gamable like a ticket system (more work) 

see also: 

* https://github.com/playmint/ds/issues/1208

**Comment by 5p0rt5BEArD** [comment]
Players should be able to go to full zones and spectate.

**Comment by chrisfarms** [comment]
for kick-off: We also think movement should (cap-permitting) allow cross zone travel

see discord: https://discord.com/channels/1115267313718018048/1116391653259882516/1225745311037784174
