### ISSUE TITLE
Tidy up tutorials/readme.md

### ISSUE THREAD

**Issue by 5p0rt5BEArD** [playmint/ds#1226]
### Tutorial folder
[This](https://github.com/playmint/ds/blob/main/tutorial/README.md)  is the page we point prospective builders to and they should be guided clearly where to go.

Top of the page should tell them to get started by following tutorial 1, then either continue with the other tutorials or come back to this page for reference.

There's a table of all the example maps that could have a few things done:
- Made one table as example-plugins and common have gone
- links added to the names - to take to the readme for each
- tutorials included - perhaps at the top of the table.
- table moved to the top of the page and replacing the current tutorial links

### Docs folder
Content in Docs folder is out of date. Most of it can be deleted but we should retain the how to play docs.
How to play docs should then also point to a running version of Hexwood 6.

### Syncing all up.
I think perhaps we have
/Docs/
 /Creation Tutorial
 /How To play
 /Reference

But leave that up to kick off

**Comment by ldunnplaymint** [comment]
I have taken this takes some distance with #1236 but I think we need some feedback from Iain. Feels like we have done enough that we can go ahead with what we have but I should have time to make more edits if necessary.
