### ISSUE TITLE
easy to miss when local deployment is "ready"

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#1227]
I waited half an hour for this, before realising it had already scrolled off the screen and I was just in some kind of Ethereum eventwatcher loop.

<img width="749" alt="Screenshot 2024-03-28 at 15 28 53" src="https://github.com/playmint/ds/assets/129759334/7c6f54ec-0d85-498d-b3f7-9ea9ad91aeb8">

**Comment by chrisfarms** [comment]
maybe for the tutorials, since we are only deploying a single tile world which comes up quick, we can just tell people to wait a couple of mins and then refresh the browser until they see the one tile instead 🤔

**Comment by ldunnplaymint** [comment]
We should re-write the readme to give a better idea on how to test if the deployment is ready
