### ISSUE TITLE
YAML vs YML

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#1228]
The Tile Fabricator exports a .yml file, not a .yaml. That confused me for a while.

<img width="751" alt="Screenshot 2024-03-28 at 15 46 17" src="https://github.com/playmint/ds/assets/129759334/3071f3e6-db1a-4d43-afca-6d7e41f4bb33">

**Comment by ldunnplaymint** [comment]
This is intentional but I can't remember why. @chrisfarms Will know the motivation.

**Comment by chrisfarms** [comment]
it's browser specific ... the browser is picking the file name and extension not us, so it will be different depending on browser.

ds-cli supports both yaml and yml extensions.
