### ISSUE TITLE
Couldn't register my building. Error: invalid number of args: wanted 4 got 5

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#1230]
ds apply -n local -k 0xd9ae05c4871908662994c9faad10e7ba3b4575b5620be86be2eb79e6d386a4d6 -f BasicFactory.yaml
Error: invalid number of args: wanted 4 got 5

<img width="1128" alt="Screenshot 2024-03-28 at 16 01 36" src="https://github.com/playmint/ds/assets/129759334/b789ee14-51b1-4dec-a3cb-106eaba1473a">

**Comment by ldunnplaymint** [comment]
Can you post the yaml for the Red Laser Radar, please?

**Comment by PlaymintDavid** [comment]
[BasicFactory (4).zip](https://github.com/playmint/ds/files/14792646/BasicFactory.4.zip)

**Comment by ldunnplaymint** [comment]
I am able to deploy those files. Maybe the error message is a red herring. What were the steps leading up to this? Is this the first error you encountered?

**Comment by chrisfarms** [comment]
there is a bug in latest deployed cli ... I am looking into it now

**Comment by chrisfarms** [comment]
this should be resolved in v0.0.24. please upgrade your ds-cli via:

```
npm install -g @playmint/ds-cli@0.0.24
```

...and try again

**Comment by PlaymintDavid** [comment]
SUCCESS!
