### ISSUE TITLE
Different imports in Tutorial 2

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#1239]
Why are these two imports different? I'd expect them to be the same.

<img width="1058" alt="Screenshot 2024-04-02 at 16 53 22" src="https://github.com/playmint/ds/assets/129759334/d4c9b115-38c5-40fc-8189-ae96f6a1fff0">

**Comment by ldunnplaymint** [comment]
One for @Steedie. Is one SquishyGate.sol and one Gate.sol?

**Comment by Steedie** [comment]
Ah, I forgot to update the imports in the first block after changing the code. I'll push commit to update the first block to match:
```solidity
import {State} from "cog/IState.sol";
import {Schema} from "@ds/schema/Schema.sol";
import {Gate} from "./Gate.sol";
```
(imports intended for SquishyGate.sol)
