### ISSUE TITLE
Please add author name in plugins

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#129]
DawnSeekers gives anyone the ability to add plugins to the game. Please could we add an author name to make it clear that plugins are authored by multiple people?

At some point maybe this is metadata that we surface. In the meantime maybe it's just in the text description?

**Comment by chrisfarms** [comment]
👍 agreed ... I have added https://github.com/playmint/ds/issues/131 which will be a prerequisite to implementing this

**Comment by ldunnplaymint** [comment]
MVP is use the deployer's wallet address
