### ISSUE TITLE
Z-order of radial buttons causes clipping issue.

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#132]
<img width="274" alt="Screenshot 2023-04-13 at 14 56 13" src="https://user-images.githubusercontent.com/129759334/231781988-71ad73cf-41be-4267-8a4e-0d17e9215225.png">

Can it always push the radial buttons to the front to avoid the clipping?

**Comment by PlaymintDavid** [comment]
Update?

**Comment by JackPlaymint** [comment]
Fixed as of today, after merging 3D-map-visuals branch
