### ISSUE TITLE
Deploy console output can get a bit messy when failing to register an already existing kind

### ISSUE THREAD

**Issue by PlaymintPaul** [playmint/ds#1336]
Seen on Windows. There were 100s of lines that look a lot like this...

![image](https://github.com/playmint/ds/assets/105200899/bd54a019-6e79-416e-9704-10f50dd2341d)

**Comment by ldunnplaymint** [comment]
- Stop retries on errors that will obviously not work on a second try (Building already registered)
- Sanitise the tx revert errors as they are extremely verbose
- Make the already registered errors more informative

**Comment by chrisfarms** [comment]
resolved: full error dump is now hidden behind the `--verbose` flag ... retries have been removed to avoid retry storm during rate limiting
