### ISSUE TITLE
Should always be clear how to deploy to your zone

### ISSUE THREAD

**Issue by PlaymintPaul** [playmint/ds#1346]
Currently the zone number is a bit hidden. You only really need to know this for deployment purposes. Can we add the deploy command for that zone to the top of the Builder Info Pane (top-right on entering)?

Something like this...
![LikeThis](https://github.com/playmint/ds/assets/105200899/859cf3cd-9b10-42dd-8a95-8bee93c20594)

**Comment by ldunnplaymint** [comment]
Add a link to where to DL ds-cli (Our readme or our npm page)
