### ISSUE TITLE
unit icon UI element stuck on screen

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#1398]
The UI element was stuck on the screen. Disappeared when my unit came into view. Might have occurred because I was switching between zones in different tabs.

<img width="1552" alt="Screenshot 2024-05-10 at 16 36 08" src="https://github.com/playmint/ds/assets/129759334/ce0b0b5b-8125-4b25-812f-2b6545c8cfc1">

**Comment by chrisfarms** [comment]
https://github.com/playmint/ds/assets/45921/0dd795ca-d158-497e-9d57-7d417aa31de9

ive seen this too ... something todo with the invisible unit hack maybe
