### ISSUE TITLE
Tile selection problems

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#142]
My cursor does not select the tile properly. Watch in the video how the selection doesn't match the cursor.

https://user-images.githubusercontent.com/129759334/232201967-8bb8f3a4-cfe9-4f9b-adad-afb2e00e5639.mp4

**Comment by ldunnplaymint** [comment]
Yeah, confirmed this fix. It was a part of Jack's last PR. We just need to get better with linking issues to PRs!
