### ISSUE TITLE
Start and destination tile selection issues

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#147]
I select a tile to bring up the radial buttons, click the move icon, then select the tile I want to move to.

The start tile remains selected even after my seeker has moved. I'm pretty sure destination tile should be selected once I've selected it. Or maybe no tiles should be selected once the destination tile is selected. Either way, the start tile should not be selected.

https://user-images.githubusercontent.com/129759334/232206749-a6ba7714-146c-4bbb-b30d-7450b4564cfc.mov

**Comment by chrisfarms** [comment]
this is an artefact of not being able to actually "select a seeker", we can only select a tile ... closing this in favour of tracking in https://github.com/playmint/ds/issues/141
