### ISSUE TITLE
I can use a building without being on an adjacent tile.

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#151]
I can use a building without being on an adjacent tile. It starts to work "Paper Factory goes brrr..." but fails when it comes to making the paper itself. Works fine when adjacent.

**Comment by PlaymintPaul** [comment]
Yeah, this is me just chucking out a message when the button is clicked. I need to hook up some more state checks before sending the log

**Comment by PlaymintDavid** [comment]
I believe @Chris-Baker is doing some work on this.

**Comment by ldunnplaymint** [comment]
This will no longer be an issue once Farm's work on the intents system is done
