### ISSUE TITLE
I can't construct buildings

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#152]
I have the necessary resources and I'm choosing an appropriate tile (I think) but I get the following message.

`16:06:36 failed CONSTRUCT_BUILDING_SEEKER: [GraphQL] action will cause batch to fail: failed dry-run of batch tx: EVM error LackOfFundForGasLimit`

https://user-images.githubusercontent.com/129759334/232822157-8d00b7ee-0835-4ce0-845b-56db0c74ba72.mov

**Comment by chrisfarms** [comment]
it's a bit blurry so I can't quite see ... but it looks like you have 98 wood ... it costs 100 to construct
