### ISSUE TITLE
Rendering at distance has some weird artefacts

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#177]
Not sure if this is just Unity being Unity but icons don't look great when scaled small.

<img width="197" alt="Screenshot 2023-04-27 at 15 00 36" src="https://user-images.githubusercontent.com/129759334/234885805-a695fa20-fc02-41aa-9fee-6ff8d23495be.png">

**Comment by ldunnplaymint** [comment]
This will be sucked up into Jack's work for this sprint, marking and planned
