### ISSUE TITLE
3D objects render before the tiles load in

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#180]
If the user loads into a mid-flight game, the beaver/building/bag objects are visible before the tiles all pop in
<img width="1528" alt="Screenshot 2023-04-28 at 12 01 28" src="https://user-images.githubusercontent.com/99176798/235132982-97c80293-9780-4a23-a3ee-354ec6a31b8f.png">

**Comment by chrisfarms** [comment]
this was fixed as a sideeffect of https://github.com/playmint/ds/pull/406
