### ISSUE TITLE
Multiple 3D objects on a tile should looks good and transition nicely

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#183]
- [x] When a beaver jumps to an occupied tile, there should only be one model but the transition should be more seamless
- [x] Shrink the buildings down slightly and push them back on the tile
- [x] Shrink down the beavers slightly so when they move to a building tile, they are a consistent size

**Comment by JackPlaymint** [comment]
Fixed with PR: https://github.com/playmint/ds/pull/205
