### ISSUE TITLE
add action to transfer ownership

### ISSUE THREAD

**Issue by chrisfarms** [playmint/ds#201]
we want an action to transfer ownership.

many things have an Owner relationship, so this might be best implemented as fairly generic `SET_OWNER(thing, newOwner)` type of action.

* only the current owner should be able to set a new owner.
* if `thing` is a Bag, then `newOwner` can be null to remove the owner (as bags can be public - owned by nobody)
* else `newOwner` must be a Player

**Comment by ldunnplaymint** [comment]
#493
