### ISSUE TITLE
Intent Shell Behaviour - Add Action bar

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#212]
Add action bar when seeker is selected that shows
- Select
- Move
- Scout
- Build
- Use
<img width="264" alt="image" src="https://github.com/playmint/ds/assets/4235606/8fa59456-90c0-462a-8f20-819a946e0c42">

**Comment by Chris-Baker** [comment]
Related: https://github.com/playmint/ds/issues/208
