### ISSUE TITLE
Construction options text is white-on-white (hard to read!)

### ISSUE THREAD

**Issue by PlaymintPaul** [playmint/ds#216]
So hard to see I genuinely didn't think the deployment was working!

![WhitesInWhiteBacking](https://github.com/playmint/ds/assets/105200899/b1e135fe-2505-4336-87fe-7a86c406838c)

**Comment by ldunnplaymint** [comment]
Worth noting that this is fine on OSX

<img width="302" alt="Screenshot 2023-05-18 at 09 12 37" src="https://github.com/playmint/ds/assets/99176798/e021fe99-dcf6-478c-b16f-24cad257086b">
