### ISSUE TITLE
Right-side panel is getting too big.

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#224]
The GUI showing the contents of the bag is pushed off the bottom of my screen, which causes a problem. Scrollbar?

<img width="1440" alt="Screenshot 2023-05-23 at 14 26 09" src="https://github.com/playmint/ds/assets/129759334/8c20ac58-efeb-453b-a8c4-a498f7d679a8">

**Comment by ldunnplaymint** [comment]
This is a bigger problem than just too much in one place, likely needs a re-design. I think we should wait until we have people using it and we have had a Jonny past.
