### ISSUE TITLE
Combat - Reward flow

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#233]
Needs fleshing out

**Comment by hypnoshock** [comment]
![Image](https://github.com/playmint/ds/assets/51167118/f960304e-3088-40a6-93f5-6f7e0a4e72a7)

Implement the rewards panel which is displayed at the bottom centre in the mockups. It might make more sense to implement it into the combat summary panel. Also depending on the mechanics of claiming, it may require a button to make the claim.

The flow might be:
- See the rewards faded out with a button to 'unlock rewards'
- Once the button is clicked, a bag is created with the rewars and the player is able to drag the items out of the bag

The tricky problem to solve is that the items won't exist until a claim has been made, and the claim process involves on-chain verification of the player's participation in the battle.
