### ISSUE TITLE
It is not possible to add to an incomplete stack in the inputs of a construct/craft

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#237]
It is not possible to add less than the required amount into an input slot and then complete the stack afterwards. 

1. Set up a building that reqires 100 kikis to craft something
2. Add 50 kikis
3. Try to add another 50 kikis

**Comment by chrisfarms** [comment]
@ldunnplaymint can you confirm that this is still an issue in `main`?

... I think removing pending might have resolved this
