### ISSUE TITLE
Constructing or Building?

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#254]
We use both terms to mean the same thing. We should pick one!
<img width="244" alt="Screenshot 2023-06-02 at 11 11 35" src="https://github.com/playmint/ds/assets/129759334/b53fbc08-6691-4218-996f-f52695e3cbfd">

**Comment by PlaymintDavid** [comment]
In case it's not clear, I'm referring to the 'build' button.

**Comment by chrisfarms** [comment]
think this is mostly because "construct" is too long to fit into the button width 😆 .... but def agree .... possible solution: use icons+tooltips for these buttons .... but maybe we should wait for proper UX/design pass as we will probably change quite a few things 🤷

**Comment by PlaymintDavid** [comment]
Construct vs Build. Hmm. See what you mean.

**Comment by ldunnplaymint** [comment]
Now that we aren't calling the beavers builders, the word feels less loaded. I wouldn't be against changing the construct button text to build. Feels friendlier anyway.

**Comment by PlaymintDavid** [comment]
Kinda agree although we're let down by the english language because building is a verb and a noun, which adds some confusion.

**Comment by ldunnplaymint** [comment]
We have changed the copy in-game, closed
