### ISSUE TITLE
Unity map sometimes "loses connection" with the chain

### ISSUE THREAD

**Issue by PlaymintPaul** [playmint/ds#266]
Sometimes I get in a position where the map doesn't update. I can put in a multi-move, and the log will show the Engineer dispatching and pending a series a MOVE_SEEKER actions, but the Engineer doesn't move. On refresh he is where he is supposed to be.

I think this mostly happens after a little bit of inactivity, and usually after having been on a different browser tab.

**Comment by chrisfarms** [comment]
which browser / OS are you seeing this on? 

how long is "a little bit of inactivity"?

are you able to reproduce it reliably? ... (I've not been able to reproduce 😞)

**Comment by PlaymintPaul** [comment]
I'll try to narrow it down. Using Firefox. Will see how it goes in Chrome

**Comment by ldunnplaymint** [comment]
I will investigate

**Comment by chrisfarms** [comment]
potential clue to what this could be: in the shell there is a queue of updates waiting to be sent to the map .... this queue does not drain while the tab is inactive as unity kinda pauses but it still fills up (in some browsers).... so when you reactiviate the tab it kinda replies everything that has happend .... potentially the browser is just stuck trying to apply many many changes

there's not much point queuing these updates, certainly not queueing them all forever ... swap to a small ring buffer or something

**Comment by chrisfarms** [comment]
closing as dup of #415
