### ISSUE TITLE
Move docs from notion to github

### ISSUE THREAD

**Issue by 5p0rt5BEArD** [playmint/ds#293]
Everything under these pages should be in the ds repo as markdown files under a top level /docs/ folder
https://www.notion.so/playmint/How-To-Docs-f2d8a9d7210847aa9b19e0207e5498bc

**Comment by 5p0rt5BEArD** [comment]
WIP in [docs branch](https://github.com/playmint/ds/tree/docs)

**Comment by PlaymintPaul** [comment]
How to play and how to build docs moved
