### ISSUE TITLE
Move path creates a bad line

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#316]
When I am creating a move path, there is a single frame where the line shoots off to one side.

<img width="1126" alt="Screenshot 2023-06-14 at 11 27 27" src="https://github.com/playmint/ds/assets/129759334/2ef64f73-9e79-4084-870b-5c2fbfdd2a59">

**Comment by ldunnplaymint** [comment]
Needs some investigation. Paul reckons it is something to do with a previous path re-appearing.
