### ISSUE TITLE
No line breaks are working in the building summary.

### ISSUE THREAD

**Issue by PlaymintPaul** [playmint/ds#322]
In the building.js, the summary field doesn't seem to like any line breaks.

I've tried "\n" and "<br>"

**Comment by chrisfarms** [comment]
the summary is intended to be a single line of text so that it can be used in various contexts.

if you want multiple lines you will need to use the`html` area, where you can get multiline using `<p></p>`, `<br />` or similar.

**Comment by Chris-Baker** [comment]
The html area is below the image though, maybe the whole section should just be html, making the image optional / customisable too
