### ISSUE TITLE
The tile animation when the game starts is nearly perfect.

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#329]
I like the wave effect a lot but when I start the game a big lump of tiles appear first. Is this by design? I've got a problem with game performance (low framerate) so maybe this is related?

https://github.com/playmint/ds/assets/129759334/02777b8f-dbd9-477e-9f3d-a37db5b8ec2b

**Comment by chrisfarms** [comment]
from planning: we are happy with something like adding a little time delay to offset it
