### ISSUE TITLE
We need a proper Favicon icon

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#337]
<img width="173" alt="Screenshot_2023-06-21_at_12 11 39" src="https://github.com/playmint/ds/assets/99176798/68e74d5f-b0c8-47df-ad30-598a09ca6ef0">

**Comment by PlaymintDavid** [comment]
I'm just commenting to say that I like the fact you called it a FLAVICON and not a FAVICON.

**Comment by Chris-Baker** [comment]
Fixed by https://github.com/playmint/ds/pull/423
