### ISSUE TITLE
Sometimes I'm unable to view the building site

### ISSUE THREAD

**Issue by PlaymintPaul** [playmint/ds#346]
Sometimes building sites get into a state where they cannot be viewed. Their tile is not highlighted when the "BUILD" command is selected

**Comment by chrisfarms** [comment]
steps to reproduce:

* start construction
* place some materials into the construction site
* cancel construction
* walk away
* come back
* try to construct on the same tile again
* _notice that you can't_

... looks like the bit that works out valid tiles can't tell the difference between a building and a construction site
