### ISSUE TITLE
"Scout" intent. If I click two available tiles in quick succession, the first becomes deselected.

### ISSUE THREAD

**Issue by PlaymintPaul** [playmint/ds#347]
1. Click scout intent
2. Quicky click one tile - it will get the binocular icon
3. Quickly click a different tile. This will get the binocular icon, but the first will lose theirs.

This only seems to happen at the beginning of going into the intent. Doing quick clicks after this first two works as expected

**Comment by ldunnplaymint** [comment]
Needs early investigation
