### ISSUE TITLE
The user should be able to merge stacks on drop

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#384]
The user should be able to complete stacks by dropping the same resource on top of them in their own bags: If there is a stack of 90 and I drop 50 on to it, the 90 becomes 100 and I have 40 left on my cursor

**Comment by ldunnplaymint** [comment]
Currently you cannot stack stackable items into stacks of over 100, reworded to make clear we need to have better error states

**Comment by PlaymintDavid** [comment]
Thank you.
