### ISSUE TITLE
allow plugins to focus the camera on a tile

### ISSUE THREAD

**Issue by chrisfarms** [playmint/ds#426]
I would like to be able to show a link in my BuildingKind plugin html that takes the camera to a location.

potentially solution: URLs

The shell can center the map on any tile via `FocusTile()` ... the shell can detect URL changes ... so...

we could allow `https://downstream.game/#/tile/-1,1,0` to jump to location, which would allow us to add links to areas of the map in plugins or share locations easily in discord.

**Comment by Chris-Baker** [comment]
Implementation detail but using Next router query parser probably makes sense. `https://downstream.game?tile=-1,1,0` or `https://downstream.game?q=-1&r=1&s=0`
