### ISSUE TITLE
It is not possible to use a building if the unit is on the same tile as it

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#464]
A unit cannot use a building that thy are on the same building as. It is possible to do this but the frontend doesn't let it happen.

It might not be a problem after bags and buildings are selectable, rather than tiles.

**Comment by chrisfarms** [comment]
this may be redundant if we make building block #461

**Comment by ldunnplaymint** [comment]
I think it might get fixed with this too https://github.com/playmint/ds/issues/355. Just keeping track as it's currently wrong.
