### ISSUE TITLE
Combat stats - implement formula to reduce power-creep

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#499]

**Comment by PlaymintPaul** [comment]
Have played with some numbers and am thinking something along these lines...

ATK & DEF = _Math.Pow(_goo_, 0.375)
LIFE = _Math.Pow(_goo_, 0.375) * 10

https://docs.google.com/spreadsheets/d/1qEYub1F2ATCghlCPdWW6Qd-nTWfR374sI3MVuGVAq00/edit#gid=0
