### ISSUE TITLE
The intro modal doesn't fit on my screen.

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#522]
<img width="1532" alt="Screenshot 2023-08-17 at 11 24 25" src="https://github.com/playmint/ds/assets/129759334/231850d2-dcdc-47ca-841b-4da1c517d6c3">

I can't see the button to close the modal window. I can see it if I zoom out. 

Need a fix for this before the extraction test.

**Comment by ldunnplaymint** [comment]
Solution for this is to just have less Text. One for @lukgib
