### ISSUE TITLE
I can't use The Great Cleanup

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#524]
<img width="559" alt="Screenshot 2023-08-18 at 13 17 41" src="https://github.com/playmint/ds/assets/129759334/bf82bd15-b8b1-40eb-bb7d-8c90a8d6e329">

When I click on it, it doesn't let me use it. Other buildings work okay.

**Comment by chrisfarms** [comment]
looks like the `contract` and `plugin` fields were missed in TheGreatCleanup.yaml manifest when porting the configs
