### ISSUE TITLE
Docasaurus adds a table to the top of each page.

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#533]
<img width="499" alt="Screenshot 2023-08-21 at 11 16 42" src="https://github.com/playmint/ds/assets/129759334/85cbfed2-efd4-4bb5-9ae0-bb666fc3696d">

Looks a bit odd. Perhaps it can be disabled?

**Comment by chrisfarms** [comment]
this metadata doesn't show in the rendered docs site (which will be deployed this sprint in #511)

**Comment by PlaymintDavid** [comment]
Okay. Perfect. Thank you.
