### ISSUE TITLE
Unfinished buildings are hard to deal with

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#577]
I started building a building last night. The graphic on the map was the 'building stump' model.

The problem was that I couldn't remember what it was that I was building and there was no indication of what the stump was for. Perhaps the GUI could default to the correct building type when I come back to the stump?

**Comment by chrisfarms** [comment]
yep we agree 😄 

closing as dup: https://github.com/playmint/ds/issues/344
