### ISSUE TITLE
Goo extractor looks full when it's empty.

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#579]
<img width="568" alt="Screenshot 2023-08-30 at 10 42 13" src="https://github.com/playmint/ds/assets/129759334/aa19fc79-b92f-4ecf-b098-c55d1de70563">

"Reservoir is 0% full"? Then what's all that pink stuff?

**Comment by chrisfarms** [comment]
from IRL: we would ultimately like the 3D model to reflect the capacity .... but until we are ready for that we would accept some form of opaque extractory thing on a more immediate timescale (one for @tboho1 to explore)
