### ISSUE TITLE
Red goo is pink

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#580]
<img width="422" alt="Screenshot 2023-08-30 at 10 43 52" src="https://github.com/playmint/ds/assets/129759334/923f5487-72db-4713-92d7-335323de25dd">

Don't try and tell me it's red!

**Comment by PlaymintPaul** [comment]
It's not red it's just resting

**Comment by chrisfarms** [comment]
it's red now so closing ... but there's a movement growing to make hexwood pink again 👀
