### ISSUE TITLE
Create a "Goo and building on tile" texture

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#586]
We need a way of showing goo and buildings on the same tile but without it looking incongruent.

**Comment by chrisfarms** [comment]
Would be good to know what the need is here? ... it seems reasonable that once constructed on, the goo is not visible

**Comment by JackPlaymint** [comment]
A recent commit of mine made the goo under buildings invisible. However it did occur to me while implementing it that when constructing an extractor building on a goo tile, as soon as the under-construction building is shown, the goo completely disappears.
I know it's still there, you know it's still there, but the player? The player thinks where is goo go? Is goo gone? Will goo return?
The player panics. "GOO IS GONE" they scream as they flee from their computer and tumble into a nearby ravine.

Having something to show that the goo is still there could have saved that player, and if we can save just one player, I think it's worth it.

**Comment by chrisfarms** [comment]
in the case of an extractor models, it might be nice if the model itself has something specific (like actually showing the goo filling up, which I think #579 is alluding too)

in the case of all other things ... the goo rates are always visible in the tile/building panel ... so I'm not sure there is really an issue with not being able to work out the gooness of a tile 🤷
