### ISSUE TITLE
Invisible units on map

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#590]
<img width="466" alt="Screenshot 2023-08-31 at 09 17 25" src="https://github.com/playmint/ds/assets/129759334/d35ad440-0e33-454f-93cc-5752084bb14d">

Invisible Farms!

**Comment by chrisfarms** [comment]
aww I miss slack... there was a whole thread for this bug where we reported ghost sightings 👻 😆 ... not seen it for ages.

for triage:this is a map<->shell sync issue ....  if we do the map refactor performance work, it makes sync issues like this go away... so either we try to tackle this issue on it's own (harder) or wait for the refactor work to make it redundent

**Comment by JackPlaymint** [comment]
*slides out of assignment... *

**Comment by chrisfarms** [comment]
haha ... if you think you know a quick fix go for it! ... but when I looked at it last (quite a while back tbf) it looked like it was all tied up with same code that kinda expects a single seeker, and keeps state of the player ... so it was a bit messy .... I think the work to try and split up the sync/json may have made it worse as sometime the player data arrives without the world data ... which confuses the map .... basically it's time for a tidy up
