### ISSUE TITLE
show name (if assigned) in OWNER and AUTHOR labels

### ISSUE THREAD

**Issue by chrisfarms** [playmint/ds#613]
in the little building/tile status label ... we should should the "name" instead of the address for the `AUTHOR` and `OWNER` labels

**Comment by chrisfarms** [comment]
this will require we allow calling `NAME_OWNED_ENTITY` on Player kinds

**Comment by 5p0rt5BEArD** [comment]
Players don't have names (only units do)
So this probaby means adding a name entry field in the player connection dialogue window


![Image](https://github.com/playmint/ds/assets/90266137/2710d824-eba6-4470-8de7-b7ff6f6c735d)
