### ISSUE TITLE
I cannot make a factory that converts one stack into a new item

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#622]
This works
```kind: BuildingKind
spec:
  name: Sorry House

  model: 04-03
  category: factory
  contract:
    file: ./Building.sol
  plugin:
    file: ./Building.js
  materials:
  - name: Gold Coin
    quantity: 5
  inputs:
  - name: Big Blue Goo
    quantity: 1
  - name: Big Blue Goo
    quantity: 1    
  outputs:
  outputs:
  - name: Big Blue Something
    quantity: 1
```

This does not work
```kind: BuildingKind
spec:
  name: Sorry House

  model: 04-03
  category: factory
  contract:
    file: ./Building.sol
  plugin:
    file: ./Building.js
  materials:
  - name: Gold Coin
    quantity: 5
  inputs:
  - name: Big Blue Goo
    quantity: 2
  outputs:
  outputs:
  - name: Big Blue Something
    quantity: 1
```

**Comment by chrisfarms** [comment]
are you seeing an error? can you describe what doesn't work?

**Comment by ldunnplaymint** [comment]
No errors. When I have one slot for 2 big blue goos, I place the goo into the factory and the craft button does not light up. I then redeployed and split the 2 goo slot into two 1 goo slots and it worked.

**Comment by chrisfarms** [comment]
this sounds like a problem with your javascript plugin ... if you have been copy pasting other factories ... make sure to either update the code in the plugin js that is deciding if the craft button should be enabled or not (or just strip out that code and have it always enabled)

**Comment by ldunnplaymint** [comment]
Ah I see! I have been being very lazy and assuming I can just change the manifest for every building I want to make. Closing as it is user error.
