### ISSUE TITLE
I can't see buildings that I don't have the resources to build

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#623]
I like to have something to aspire to in the game but the buildings I don't have resources for are hidden.

**Comment by ldunnplaymint** [comment]
You currently can do this, though it is not a nice flow:
Select build > untick the "Hide unconstructable" tick box > Select anything from the drop down > Select a tile > Read the material cost in the box

We are intending on solving the building filtering properly with the itemKind work
