### ISSUE TITLE
I want to be able to clean up combat reward bags

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#630]
Sometimes I don't want the 10 goo from decorations or I just don't have enough space and cannot be bothered to trek about inventory managing. I want to have the ability to say "Go away" to some of these reward bags, it annoys me I have to litter the place.

**Comment by JackPlaymint** [comment]
I was thinking about this after you and David and Chris lost all your resources building the big goo extractors. Could we have a "Donate to public fund" type option for goo you don't want, so people who have lost all their goo can be saved by going to a goo charity. Would that even work?
