### ISSUE TITLE
I want to know the list of building models/combinations I can pick from

### ISSUE THREAD

**Issue by chrisfarms** [playmint/ds#632]
I'm flying blind when picking a building model for my custom BuildingKind, there should be a nice way to work out what I am going to get (at least docs, but maybe a tool)

**Comment by JackPlaymint** [comment]
I could make some pictures of the totem pieces and add them to a docs page with their IDs. I've not touched the docs yet so would be good to have a go at that.

**Comment by chrisfarms** [comment]
sounds good to me!
