### ISSUE TITLE
I want to have the ability to put buildings in my bag slots

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#635]
I want to be able to make a building, collapse it into an item and then redeploy it else where. 

I basically can already with knocking buildings down but I want them to keep state.

For example, I want to be a travelling vendor and to pop my shop up at a moments notice

**Comment by ldunnplaymint** [comment]
I would also like to be able to put a unit into a bag slot on a building, put that building into my bad, then deploy the building and russian doll the unit out again

**Comment by PlaymintPaul** [comment]
...
