### ISSUE TITLE
I'd like more in-depth building customisation

### ISSUE THREAD

**Issue by JackPlaymint** [playmint/ds#640]
Ok this is a really unimportant one, but I thought I'd mention it anyway.

I feel like the current system of choosing two prebuilt totems doesn't allow for enough freedom of expression.
We could get a similar style, while also massively expanding customisation options if we went with a base->greeble approach.

Essentially you'd start out with a base shape (like a cube or a cylinder or even something more detailed like a barrel), and then you would stick 'greebles' onto the surface of the base. The greebles could be anything from doors and windows to more abstract things like eyeballs etc.

There would be a limit to how many greebles you could place on a base, but the greeble type and placement would be entirely up to the player. We could also allow more than one 'floor', similar to the totem stacking we currently have.

Obviously this would require a more in-depth customisation screen.
My recommendation would be to have a separate page on the site with a 'building creator', which would allow you to make a building and then spit out a string that you would paste into your building contract so that the game knows what it needs to recreate when showing your building.

One thing we would need to sacrifice with this approach is baked ambient occlusion in the model textures.
We could combat that in a couple of ways:
The first and most straight forward is relying on our screen-space AO post process. We already have this effect in the game so it wouldn't be an extra performance hit, however the AO it applies to models is less defined than pre-baked AO. The detailed crevices of the models would be less contrastingly dark.

**Comment by chrisfarms** [comment]
this sounds like an interesting direction to me, ... I think this deserves a thread in dev-threads to get more eyes/discussion on it

**Comment by ldunnplaymint** [comment]
Thread in discord
