### ISSUE TITLE
Unity Content Error on Metamask login

### ISSUE THREAD

**Issue by ChrisWh99** [playmint/ds#641]
I got the below message when I signed in via the Metamask option:

<img width="731" alt="image" src="https://github.com/playmint/ds/assets/133345369/1c7a2b14-971a-486e-8348-deadfc2f2f7d">

Disconnected wallet, signed in again and the issue did not repeat.

**Comment by chrisfarms** [comment]
thanks 🙏 

closing this issue as we are tracking it in:

* #610
