### ISSUE TITLE
Glitchy when scrolling 

### ISSUE THREAD

**Issue by ChrisWh99** [playmint/ds#642]
I noticed it last night and this morning, but the map's a bit glitchy when scrolling and dragging around with the mouse.

**Comment by chrisfarms** [comment]
I believe you might be seeing:

* #607 

can you confirm if the glitching you are seeing goes away when you do not have a building plugin on the screen (ie just click on a random empty tile)?

**Comment by ChrisWh99** [comment]
Yes, that's it! Only when a building plug-in is selected.

**Comment by chrisfarms** [comment]
k thanks ... will close this in favor of tracking with the existing ticket 🙏
