### ISSUE TITLE
Make it easier to see item stats

### ISSUE THREAD

**Issue by ChrisWh99** [playmint/ds#649]
I might be impatient but...

It would be nice for the little window to appear slightly quicker when hovering over the item in a bag.

**Comment by chrisfarms** [comment]
are you referring to the "tooltip"? ... this thing:

![Screenshot 2023-09-06 at 12 02 02](https://github.com/playmint/ds/assets/45921/dc243499-0921-4cfe-9081-17252829976e)

**Comment by ChrisWh99** [comment]
Yep

**Comment by chrisfarms** [comment]
thanks.

this is currently a native browser tooltip which we have no control over.... I agree we should be surfacing this information more prominently - it's basically a hidden feature at this point

... that might mean using non-native tooltips that show faster ... or it might mean just a different UI entirely
