### ISSUE TITLE
New combat deletes rewards bag from attacking tile

### ISSUE THREAD

**Issue by 5p0rt5BEArD** [playmint/ds#654]
- Started with two decorative buildings next to each other
- Attack the first one and observe bag on tile after victory
- move to tile with bag and attack the second building from there
- bag is removed from tile
- bag does not return after combat is complete

https://github.com/playmint/ds/assets/90266137/66e1afd7-c1d3-468d-9d2e-a7beb919098c

**Comment by chrisfarms** [comment]
dup or at least related to: #629
