### ISSUE TITLE
building plugin still displays in "use" mode if selected during move

### ISSUE THREAD

**Issue by ChrisWh99** [playmint/ds#658]
Although the transaction fails, it 'feels' like you can extract from a distance when you can't.

<img width="1842" alt="image" src="https://github.com/playmint/ds/assets/133345369/9b8203e0-8575-4a48-9ff4-60f55e74344e">

**Comment by ChrisWh99** [comment]
Yes, agreed.  Wasn't sure how to write it.

**Comment by chrisfarms** [comment]
ah ok I got it ... steps to reproduce:

* have unit selected, while standing next to a building
* initiate a move somewhere
* quickly before you have actually moved; select the building next to you
* ... you now have a building selected as if you are standing next to it, but you arn't

**Comment by ChrisWh99** [comment]
I hadn't initiated a move, I was just next to the Big Blue Goo Extractor.  Clicked on the Big Green Goo and the select unit and I got the image as above.

I had just extracted one Big Blue Goo though.

**Comment by chrisfarms** [comment]
ah nice ... yeah same bug ... tile selection needs to update on select seeker ... we purposely removed this due to a performance thing .... will bring it back after we have sorted perf 👍
