### ISSUE TITLE
Tool tip text is low resolution and inconsistent with all other font

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#67]
<img width="743" alt="Screenshot 2023-03-30 at 15 53 12" src="https://user-images.githubusercontent.com/99176798/228877054-aec21984-ff1a-4bd4-a392-e9636c771e0b.png">

**Comment by chrisfarms** [comment]
after we have implemented https://github.com/playmint/ds/issues/104 .... can we just remove the popup entirely?

the tile highlights (which didn't exist when the popup was first made) do a good job of enticing a left-click ... and the right-click can remain an undocumented (for now) shortcut to performing the same thing as the buttons in #104
