### ISSUE TITLE
Add Tile Coordinates

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#68]
We currently do not show the tile coordinates on a selected tile in the tile info display

<img width="310" alt="Screenshot 2023-03-30 at 15 55 59" src="https://user-images.githubusercontent.com/99176798/228877599-3eeafb5c-5b7b-49d0-8c35-d46368e281bd.png">

**Comment by chrisfarms** [comment]
resolved by: https://github.com/playmint/ds/pull/161
