### ISSUE TITLE
Bad framerate on docs site

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#702]
https://github.com/playmint/ds/assets/129759334/54c297d0-be38-4980-8a27-2352486dd926

The docs site is laggy when I scroll. Doesn't feel good.

**Comment by chrisfarms** [comment]
can you confirm this is an issue only for that particular docs page (ie can you try any of the other docs links) .... since that particular page has the embedded diagram, and I'd like to rule out if that is causing the issue

**Comment by PlaymintDavid** [comment]
The page has now been shortened and I can't find the issue on any page, so I think you're okay to close this.
