### ISSUE TITLE
Item plugin display can cause the unit info panel to get pushed off screen

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#704]
<img width="526" alt="Screenshot 2023-10-10 at 11 24 59" src="https://github.com/playmint/ds/assets/99176798/656c51ee-b25b-4084-a4ce-2366fd408aa0">

**Comment by hypnoshock** [comment]
Something to try might be to make the item panel `position:absolute` and not set a position. I the same for the quest panel which means that it doesn't resize the grid if it becomes taller than the row. Not sure it's the *ultimate* fix but at least it should stop it from looking broken

**Comment by hypnoshock** [comment]
Since the UI overhaul this no longer happens. The item plugin will overlap the quest panel instead
