### ISSUE TITLE
Would be nice to be able to hide Factory crafting inputs in the Javascript

### ISSUE THREAD

**Issue by PlaymintPaul** [playmint/ds#713]
I can hide the button that lets you craft. But I can't hide the INPUT/OUTPUT slots

**Comment by hypnoshock** [comment]
There is a CSS hack way to do this which I did for Bag Beasts however there does need to be an easy way of doing this without relying on CSS

**Comment by chrisfarms** [comment]
this would be resolved by the work related to:

* #456 

... where it becomes up to the plugin author to decide what to show
