### ISSUE TITLE
We have stopped showing the combat screen when starting combat

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#721]
Not sure if this was intentional but I just don't get to see how powerful the enemy is before I attack them.

**Comment by chrisfarms** [comment]
it was intensional ... seeing how powerful the enemy is (and how powerful your self is) should be resolved when we get around to showing the building/unit stats for whatever is selected

**Comment by ldunnplaymint** [comment]
Fair enough. In that case, I think the fact that I need to open the combat modal to resolve the combat feels pretty weird. We should be able to resolve it in the right hand panel or it should auto resolve. I can put a different ticket in.

**Comment by chrisfarms** [comment]
yeah I agree ... the model feels like the "I want to see details" ... and the common actions should not need me to open it

but I'm not sure how much combat is staying like this long term anyway so 🤷

**Comment by PlaymintPaul** [comment]
> Fair enough. In that case, I think the fact that I need to open the combat modal to resolve the combat feels pretty weird. We should be able to resolve it in the right hand panel or it should auto resolve. I can put a different ticket in.

There already an issue for that
