### ISSUE TITLE
reformat code blocks in docs to avoid getting clipped off screen

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#728]
<img width="1532" alt="Screenshot 2023-10-17 at 14 43 42" src="https://github.com/playmint/ds/assets/129759334/c0b8d800-a263-43a9-b610-71ac28b2948d">

There's no text wrap on this docs page. Not sure if that's deliberate.

**Comment by ldunnplaymint** [comment]
We are going to write the docs next sprint so this issue will be resolved during that work
