### ISSUE TITLE
Once all of a QUESTs criteria have been completed, it stay completed

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#737]
Example:
**Verification Error** 
1. Go to Registration Office
2. Collect Registration Receipt

I can do 1 and 2, if I then move away, 1 becomes incomplete. Feels like it should just stay in the "Completed" state at that point instead of un checking task 1.

I get in the situation where you go to the building and immediately leave it should uncheck but it seems weird you can uncomplete a quest.

**Comment by PlaymintPaul** [comment]
Its annoying, but there's no good way of avoiding this on the blockchain unfortunately. 

I'm avoiding using the Move To task after the first couple of quests for this reason,  but I think it's needed for the first few to explain how the game works.

**Comment by chrisfarms** [comment]
I think wording tasks to be statements like "be at registration office" and "have registration receipt" rather than commands like "go to registration office", "get regitration receipt" would mostly avoid the confusion here

**Comment by ldunnplaymint** [comment]
Yeah, that could help make it clearer. I also think, in a future version, having some flashy animation when the collect button appears might stop people missing it.
