### ISSUE TITLE
If a Quest becomes available to complete. Can we maximise it in the Quest panel?

### ISSUE THREAD

**Issue by PlaymintPaul** [playmint/ds#763]
At the moment you have to know you've completed it, if it's not maximised

**Comment by hypnoshock** [comment]
Before we go ahead and do this, would finishing off the design with the progress bar solve this issue?

**Comment by hypnoshock** [comment]
There is now a progress bar on minimised quests. The bar will also be green if the quest can be completed which serves as a call to action. Let's see if this solves the issue and go from there.
