### ISSUE TITLE
We are using the shield as the favicon icon

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#770]
<img width="331" alt="image" src="https://github.com/playmint/ds/assets/99176798/010279a3-26df-4265-82da-6bb3cb3b976d">

<img width="219" alt="Screenshot 2023-10-27 at 09 13 23" src="https://github.com/playmint/ds/assets/99176798/0c1b4d51-96a7-491e-bdc8-b39e2bd06378">

**Comment by ldunnplaymint** [comment]
Updated the issue

**Comment by ldunnplaymint** [comment]
![BlackFav](https://github.com/playmint/ds/assets/99176798/9ac6b0cc-2820-4477-887f-02b0bc74b70c)
![OrangeFav](https://github.com/playmint/ds/assets/99176798/74f1335b-6b43-47e1-85b3-e1b82f55c67b)

Here are the files! We need to decide which

**Comment by JackPlaymint** [comment]
Did we decide which? My vote is for the orange and white one as the black one doesn't show up well on my dark-theme browser

**Comment by chrisfarms** [comment]
that sounds like a decent reason to me .... go orange/white
