### ISSUE TITLE
Combat Reward Goo Stuck

### ISSUE THREAD

**Issue by ChrisWh99** [playmint/ds#775]
<img width="249" alt="image" src="https://github.com/playmint/ds/assets/133345369/a6b656f5-5d46-44d3-b974-f892dba2dc09">

There's a little bit of blue goo left in my combat reward bag.  I have space to claim but it's stuck in the bag with the spinning circle.

**Comment by chrisfarms** [comment]
had a look on his machine ... it fixed itself ... which means it's either a slow tx or got out of sync ... so might be hard to reproduce

don't think it's actually related to combat rewards, more like a general stuck tx
