### ISSUE TITLE
Change the target focus QUEST icon for a Crosshair

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#794]
A cross hair is less confusing

**Comment by ldunnplaymint** [comment]
Need an icon

**Comment by chrisfarms** [comment]
![Image](https://github.com/playmint/ds/assets/45921/cd8d7a10-4f67-4bbb-9644-7ea22f2ba730)



![Image](https://github.com/playmint/ds/assets/45921/9353aa62-aca8-4683-bff1-0255781d896b)

this one is in the figma
