### ISSUE TITLE
Title for red goo tile doesn't match the visuals

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#808]
Minor issue, but (to me) it would make more sense if the tooltip says "this tile has some red goo" on tiles where visually there is some red goo. I know that all (?) tiles have some amount of red goo so the tooltip is not inaccurate, just not intuitive.

<img width="869" alt="Screenshot 2023-10-31 at 09 42 22" src="https://github.com/playmint/ds/assets/129759334/cbc2ec85-c3ff-4ee0-a34c-70f4dd2c17d8">

**Comment by chrisfarms** [comment]
yeah this is a bug ... only tiles that visually have the goo splodges should be displaying a "{RED/GREEN/BLUE} GOO TILE" just as you expect... the threshold for the tile description is probably out of date with some goo rate changes
