### ISSUE TITLE
Deletion Duty language

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#810]
The second part should not be in parenthesis. Suggest "Delete any Building or Bug. Extractors should pose no problem."

<img width="334" alt="Screenshot 2023-10-31 at 09 53 34" src="https://github.com/playmint/ds/assets/129759334/3ad84ee7-2afa-44c2-af7e-aea59b7d4c52">

**Comment by ldunnplaymint** [comment]
Done
