### ISSUE TITLE
playmint.com: Linkrot! testnet.downstream.game

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#823]
_Current state of the world_ links to testnet.downstream.game which is dead.

<img width="884" alt="Screenshot 2023-10-31 at 16 27 18" src="https://github.com/playmint/ds/assets/129759334/d0b358c6-f3d9-4072-a68c-27398cd8f587">

**Comment by ldunnplaymint** [comment]
Should be resolved by the landing page implemention

**Comment by ldunnplaymint** [comment]
The link should be downstream.game

**Comment by PlaymintDavid** [comment]
https://downstream.game/ resolves to testnet.downstream.game which is broken.

**Comment by ldunnplaymint** [comment]
Sorry, I should have mentioned. Farms will be changing all of the URLs and the downstream.game link resolving to the correct deployment should be solved in that piece of work.

**Comment by chrisfarms** [comment]
downstream.game will be landing page ... which is still being built
