### ISSUE TITLE
unclear how I get the Deletion Tool

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#839]
Where do I get the Deletion Tool. Shouldn't it tell me?

<img width="853" alt="Screenshot 2023-11-01 at 16 42 06" src="https://github.com/playmint/ds/assets/129759334/7f4ede67-697e-4fbe-b3aa-ca66704cf06a">

**Comment by ldunnplaymint** [comment]
If you click the target icon in the quest it moves the camera to the building in question. The text probs should be a bit more specific though.

**Comment by PlaymintDavid** [comment]
Some helper text would be good.

**Comment by ldunnplaymint** [comment]
Out of scope for this release. Realistically we need a new feature to plug the gaps in map readability.
