### ISSUE TITLE
Construction is unnecessarily fussy about inventory slots

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#88]
I had enough wood to construct my first building, but the action failed until I put the wood in a certain place in my inventory.

<img width="304" alt="Screenshot 2023-04-03 at 14 11 08" src="https://user-images.githubusercontent.com/129759334/229520347-b5f6caca-cd10-4d77-b39a-dc3c8981161e.png">

**Comment by chrisfarms** [comment]
Yep this is currently hacky. The "magically stealing stuff from a specific slot in your bag" thing is just a stop-gap until there is a UI to drag-n-drop the required resources. This issue also affects crafting, which also steals things from your bag.

We should not be having anything stolen from bags without explicit inventory dragy-droppy action.
