### ISSUE TITLE
Advanced example buildings for the Workshop

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#883]
- Calling an action that isn't craft
- Using the payload param to do optional things in the use function

Potentially a locker building?

**Comment by hypnoshock** [comment]
@5p0rt5BEArD I'm not sure if this is linked to the work you're already doing in https://github.com/playmint/ds/pull/886

Looks like it isn't so perhaps I could make a locker building unless that was something you specifically wanted to do?

**Comment by 5p0rt5BEArD** [comment]
I'd be very happy for you to make a locker building!
It wont affect the work I'm doing on the basicfactory code - just put any example code in contracts/src/example-plugins
