### ISSUE TITLE
INVESTIGATE - User's quest was removed from the UI

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#920]
A demo user encountered an issue where the orientation quest ended early but was still available from the Control tower.

If the user attempted to take the Orientation quest again from the tower, an error threw. The error seemed to suggest taking the quest twice wasn't possible. 

The instance of the game (Hexwood3) is still alive as of this post (2pm 20/11/23).

From the user's perspective, they had no active quests and were being offered a quest they had already partially completed.

## From conversation on slack

I THINK it is this one: `unit1445`

Units I think it COULD be?
- `unit058a`
- `unit01e2`
- `unit04a1`

Other Units I don't THINK are relevant
- `unit0945`
- `unit0a28`

**Comment by hypnoshock** [comment]
Are there any steps to reproduce this?
I'm not 100% sure what's happening here. So when you say 'select the quest', does that mean they expanded the quest from the minimised state or does it mean they accepted the quest from a building?
And does 'leave the UI' mean that it disappeared?

**Comment by ldunnplaymint** [comment]
Updated the body, I think it clears up your questions
