### ISSUE TITLE
Pending transfer logic is not looking at the "from" slots to determine if it is complete

### ISSUE THREAD

**Issue by Chris-Baker** [playmint/ds#93]
## Description
When we get partial updates back from the indexer the pending states for slots can be removed because the "to" slot has the correct balance, however, the "from" slot can have the incorrect balance. When the pending state is removed all slots become interactable again which allows the UI to get into an illegal state.

## Steps to reproduce
1. Pick up a stack of items
2. Drop many single items on several slots
3. Drop the remaining items on another slot
4. Observe as the stack of items on the initial slot becomes interactable before finally resolving and being removed as expected

## Notes for fixing
We should be tracking the balance in the "from" slot when we filter out completed transfers. We will also need to take into account that multiple transfers can share the same "from" slot

**Comment by Chris-Baker** [comment]
related: https://github.com/playmint/cog/issues/16

**Comment by chrisfarms** [comment]
this is no longer relevent as that system was removed ... dispatch() now returns a promise so we can reimplement pending using that when it comes to it
