### ISSUE TITLE
Inconsistent and unintuitive building name. DummyBuilding.

### ISSUE THREAD

**Issue by PlaymintDavid** [playmint/ds#94]
I am thrilled that I can construct a building on the map. I don't even care that it just says 'hello'.

Could we name it 'Tower of Hello' in both these places, to add some consistency? Currently it says _DummyBuilding_ and _DUMMYBUILDINGGREETER_.

<img width="253" alt="Screenshot 2023-04-04 at 15 33 56" src="https://user-images.githubusercontent.com/129759334/229826987-1f386fff-8345-4773-9f1f-35b04bbb760a.png">

<img width="269" alt="Screenshot 2023-04-04 at 15 34 08" src="https://user-images.githubusercontent.com/129759334/229827043-734c5b2f-78c7-4f86-9015-0645c3409687.png">

**Comment by chrisfarms** [comment]
checkout [this relevent slack thread](https://playmint.slack.com/archives/C03GZ6JAFK3/p1679646905839609?thread_ts=1679646905.839609&cid=C03GZ6JAFK3) from last week. plan is to have a "flag" to replace the test building

**Comment by PlaymintDavid** [comment]
Sounds good. As you see fit.

For what it's worth, I quite liked the building because it gave me a wave when I clicked on the button.
