### ISSUE TITLE
CRAFT_STACKABLE doesn't seem to work

### ISSUE THREAD

**Issue by PlaymintPaul** [playmint/ds#96]
All attempts have resulted in a transaction failure. Attached are two screenshots. The equipable one works, the stackable one doesn't

![staackable](https://user-images.githubusercontent.com/105200899/229834783-b9802bb1-7ddf-4f95-827a-484771407f61.png)

![equipable](https://user-images.githubusercontent.com/105200899/229835000-541b860d-f480-4ccf-8a58-4ffb25a05d97.png)

**Comment by chrisfarms** [comment]
resolved in slack thread:

> the "stackable-ness" is part of the itemkind ... so you need to register a specific stackable version of the item during REGISTER_ITEM if you want to be able to use CRAFT_STACKABLE
