### ISSUE TITLE
Choose map on deployment

### ISSUE THREAD

**Issue by 5p0rt5BEArD** [playmint/ds#969]
I'd like a set of "maps' (folders with a collection of manifests) to be in the repo.
Then at deploy time, be able to choose which one to use.

This may be an environment variable or parameter but needs to be an option for local builds and github action deploys.

**Comment by 5p0rt5BEArD** [comment]
In display-buildings we have

-\contracts\src\maps\
--\arena-1kx\
--\team-vaniila\
--\tiny\

Should work out the best place for these and the relationship with Fixtures as part of this

**Comment by 5p0rt5BEArD** [comment]
This work is largely completed by #994, which introduces the MAP variable to the make command line so the iny map can be deployed using `make dev MAP=tiny`

For deploying in production we can just edit the entrypoint script in a branch before deploying from there

The remaining tasks on this issue are:

- Move fixtures to a maps/default folder and default to that when no MAP is given
- Possibly allow manifests to be shared across maps , e.g. to allow extractors to be defined once and used in multiple maps. This feels like a whole other issue though

**Comment by ldunnplaymint** [comment]
Superseded by #1012 #1013 #1014 #1015
