### ISSUE TITLE
Remove Unit corpses

### ISSUE THREAD

**Issue by 5p0rt5BEArD** [playmint/ds#972]
Units stay on the map forever which is not good for repeating experiences on the same map with different players (or just new burners)

Not sure of proper solution but it could be a frontend cheat for now

- Units that have not been interacted with for X blocks are not shown. Filtered out by graphql into a separate list

bonus

- PLayer account dialogue shows any dead units and you can revive them

bonus (or optimisation)

- there is an action to delete all "dead" units from onchain state

**Comment by ldunnplaymint** [comment]
Hide units in the frontend who haven't moved for a set amount of time (Use the next locations block)
