### ISSUE TITLE
Make cocktail hut a working example of Display Buildings

### ISSUE THREAD

**Issue by 5p0rt5BEArD** [playmint/ds#983]
It already does use the alwaysActive flag and returns map data - it would be better if it correctly found building Ids to connect to.

Make it a good example.

Perhaps a wider point is that the Cocktail hut should become a good example of all plugin features (e.g. State Storge)

**Comment by ldunnplaymint** [comment]
https://github.com/playmint/ds/blob/always-active-plugins/contracts/src/example-plugins/Cocktails/CocktailHut.js

**Comment by ldunnplaymint** [comment]
Related to [#974](https://github.com/playmint/ds/issues/974)
