### ISSUE TITLE
CLI publish should publish a release candidate and then bump the number

### ISSUE THREAD

**Issue by 5p0rt5BEArD** [playmint/ds#989]
Curren behavior is to publish the new version directly, using current version number and then increase the version number. We want two things to be different:

1. The published version should be the current version in code and then the version number is increased. This means local builds will correctly be a version ahead of the published one
2. ~~The published version should be a candidate, available for install,  but not the default install until it gets promoted. This wqas attempted in the 1kx hackathon branch but it the rc still seemed to be the default being downloaded so publish command has not been merged in~~

**Comment by 5p0rt5BEArD** [comment]
Chatting to @chrisfarms - we probably don't want to do 2.

**Comment by ldunnplaymint** [comment]
Updated body
