### ISSUE TITLE
Plugin buttons can be overloaded with text

### ISSUE THREAD

**Issue by ldunnplaymint** [playmint/ds#996]
I don't know if this is really a bug. I guess we could shrink text as the string gets longer or something but that doesn't feel like it would result in nice outcomes.

Potentially we need to have a "Max width" for the button which we just communicate to people?

<img width="298" alt="image" src="https://github.com/playmint/ds/assets/99176798/b63acc59-3fff-4780-8254-949e3a7f2496">

**Comment by chrisfarms** [comment]
yeah think `overflow:hidden` + `text-overflow: elipsis`

**Comment by chrisfarms** [comment]
resolved by: https://github.com/playmint/ds/pull/1021
