### ISSUE TITLE
Extractor plugin - Send the goo directly to the Unit's inventory

### ISSUE THREAD

**Issue by PlaymintPaul** [playmint/ds#997]
Currently, when an extractor is used the plugin will add 100 goo to the item slot which can then be dragged into the Unit's inventory.

Suggestion is to remove the Item Slot. Pressing the button will directly send the goo to the Unit's inventory.

Some feedback should be added to the plugin to explain what has happened once the button is pressed
- "100 Green goo added to inventory"
- "Not enough inventory space to extract goo"
- "No goo in the extractor"

![extractor](https://github.com/playmint/ds/assets/105200899/bcccb621-0ff8-44e3-bbdd-2b20ab1dc618)

**Comment by ldunnplaymint** [comment]
We need to work out how to clear the text (What triggers the text to clear?)

**Comment by PlaymintPaul** [comment]
Status update just has to show why the button is disabled. E.g. No room in inventory

**Comment by chrisfarms** [comment]
superceed by #1126
