### ISSUE TITLE
Crafting plugin - "Add items" button and place output into inventory

### ISSUE THREAD

**Issue by PlaymintPaul** [playmint/ds#998]
Currently, crafting requires a lot of clicks and item dragging. To reduce this

1. "Add Items" button put on plugin. This will place the items from the unit's inventory into the item slots.
2. "Craft" button will output the item directly into the unit's inventory
3. Feedback added to the plugin to explain what is happening when a button is clicked:
- "Insufficient items to add"
- "Ready to craft"
- "Item added to inventory"
- "No space in inventory to place crafted item"
![Crafting_insufficient](https://github.com/playmint/ds/assets/105200899/7ee48ed0-3051-482e-aae4-d0368661a709)
![Crafting_ready](https://github.com/playmint/ds/assets/105200899/6f70de33-cc87-4b90-ac75-96b97d8d5d92)
![Crafting_added](https://github.com/playmint/ds/assets/105200899/de422ae2-e057-480f-a859-86169a7d610d)

**Comment by ldunnplaymint** [comment]
Code for finding things in the inventory that find the items from the recipe is the same as the building construction code. We should be able to reuse it to achieve most of this task.
