### ISSUE TITLE
Instantly resolve combat, after a delay

### ISSUE THREAD

**Issue by PlaymintPaul** [playmint/ds#999]
When a player initiates combat:
1. The tiles should get the red combat highlight (as they currently do) and the combat session stats are viewable.
1b. The time when the combat will happen is visible.
2. Combat hasn't begun yet. Units can still join/leave the "session", but no damage is being done
3. When the combat time is reached, the combat is instantly resolved.
- Use the current combat system. Instead of one tick per 2 secs, loop through all the ticks instantly

4. The act of starting a combat also "pays" for the resolve at the end of the combat. This means that when the combat has happened, it is immediately resolved and the game state updated.

![CombatSummaryPng](https://github.com/playmint/ds/assets/105200899/13508e4d-1742-43bc-aa65-717ede2fd5dd)
![Screenshot 2024-01-26 115021](https://github.com/playmint/ds/assets/105200899/e63f2987-4094-4c80-9b55-4831da10ec79)

**Comment by ldunnplaymint** [comment]
For 4: Clients should just automatically look to resolve combats
